version: '3'

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "homeht"
      POSTGRES_PASSWORD: "homeht"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
